### ISSUE TITLE
scaled data mse:  nan

### ISSUE THREAD

**Issue by doncat99** [christsaizyt/US-Stock-Market-Prediction-by-LSTM#1]
############## validation on test data ############## 
scaled data mse:  0.0229374753975
 ############## validation on train/test lately data ############## 
scaled data mse:  0.0065217987884
 ############## validation on valid data ############## 
scaled data mse:  0.0752756587974
 ############## validation on lately data ############## 
scaled data mse:  nan

I run the script with the outcome above, can't figure out when goes wrong.

**Comment by christsaizyt** [comment]
My suggestion is the predictions work when the mse (for validation) is small enough, 

according to the outcomes, the validation mse is 0.075… it’s pretty small I though. 

You can check the predictions for the lately dates.

**Comment by christsaizyt** [comment]
scaled data mse for lately data is nan. It's because there's no label for lately data.

**Comment by doncat99** [comment]
Christ, I found an interesting approach, here is the link for your reference.

https://github.com/carpedm20/text-based-game-rl-tensorflow

I am working on adding a DQN network on the top of your LSTM model to see if Reinforcement learning could help enhance the performance.

**Comment by christsaizyt** [comment]
close issue
